### ISSUE TITLE
汪磊老师，提个小问题

### ISSUE THREAD

**Issue by lovedaan** [Micua/angular-boilerplate#1]
我git clone你这个angular-boilerplate到本地， 然后npm start运行，cmd报错，也打不开9000端口的地址，报错信息：
Hit CTRL-C to stop the server
[Mon, 08 Aug 2016 07:37:53 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ResponseStream.(anonymous function) [as setHeader](E:NodeJscode06moveicatnode_modulesunionlibresponse-stream.js:88:34)
    at E:\NodeJs\code06\moveicat\node_modules\ecstatic\lib\ecstatic\showdir.js:43:13
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\test\nodejs\node.exe" "E:\test\nvm\npm\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! angular-boilerplate@1.0.0 start: `hs -a localhost -p 9000 -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-boilerplate@1.0.0 start script 'hs -a localhost -p 9000 -o'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hs -a localhost -p 9000 -o
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

要怎么解决呢，麻烦老师可以回复一下我邮件（897955713@qq.com），灰常感谢！

**Comment by zce** [comment]
你的这问题好像是node版本的问题，http-server这个包在node版本为6+时需要升级到最新版本，请在项目下重新执行

``` bash
npm install http-server --save-dev
```

**Comment by CodeMagic6** [comment]
我用的Node 5.7.0也是报相同的错误。改成Node 5.5.0之后  npm install http-server --save-dev就好了。
