### ISSUE TITLE
汪磊老师，还有一个问题

### ISSUE THREAD

**Issue by lovedaan** [Micua/angular-boilerplate#2]
就是我安装nvm 还切换node版本，为什么可以切换node版本，但是npm的版本确没有对应切换，而且我用nvm install 5.12.0 比如我下载这这个node，但是下载完里面没有npm这个文件。。。这是怎么回事呢，是我npm环境变量配错了么

**Comment by zce** [comment]
通过nvm安装node的不同版本，正确情况下会在nvm的目录中出现对应版本的文件夹，在该文件夹中会
![11](https://cloud.githubusercontent.com/assets/6166576/17474176/46a5f448-5d87-11e6-8732-0411e0cbe561.png)
