### ISSUE TITLE
有个关于路由地址的小问题

### ISSUE THREAD

**Issue by CodeMagic6** [Micua/angular-boilerplate#3]
自己写了一个路由demo，我在app.js里面路由规定了
$routeProvider.when('/one','第一个页面').when('/two',第二个页面)。但是我写好app.js 和one/controller/js，two/controller.js，运行后点击发现，网页地址栏并不是想象中的selfdemo/index.html#/one，而是多了一个#，并且自己写的/被转义成了%2F，这个样子：selfdemo/index.html#!#%2Fone

**Comment by zce** [comment]
a链接的href属性有问题吧
